apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-certificate
  #namespace: nginx
spec:
  secretName: nginx-certificate-secret
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - nginx-test.w1.lv